name: CICD_PR

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
  pull_request_target:
  
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        formfactor:
          - name: mobile
            width: 414
            height: 736
            preset: "desktop"
          # - name: desktop
          #   width: 1920
          #   height: 1080
          #   preset: "desktop"
          # - name: tablet
          #   width: 768
          #   height: 1024
          #   preset: "desktop"
          # - name: laptop
          #   width: 1366
          #   height: 768
          #   preset: "desktop"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Find project directory with package.json
        id: find_dir
        run: |
          PROJECT_DIR=$(find . -name package.json -exec dirname {} \; | head -n 1)
          echo "PROJECT_DIR=$PROJECT_DIR" >> $GITHUB_ENV
          echo "Found project directory: $PROJECT_DIR"

      - name: Install Lighthouse CI and Dependencies
        run: |
          cd ${{ env.PROJECT_DIR }}
          npm install -g @lhci/cli
          npm install

      - name: Build React App
        run: |
          cd ${{ env.PROJECT_DIR }}
          export NODE_OPTIONS=--openssl-legacy-provider
          SKIP_PREFLIGHT_CHECK=true npm run build

      - name: Create Lighthouse CI Config
        run: |
          cd ${{ env.PROJECT_DIR }}
          cat << EOF > .lighthouserc.${{ matrix.formfactor.name }}.json
          {
            "ci": {
              "collect": {
                "numberOfRuns": 1,
                "url": [
                "http://localhost:3000/"
                ],
                "settings": {
                  "preset": "${{ matrix.formfactor.preset }}",
                  "emulatedFormFactor": "${{ matrix.formfactor.name }}",
                  "screenEmulation": {
                    "mobile": false,
                    "width": ${{ matrix.formfactor.width }},
                    "height": ${{ matrix.formfactor.height }},
                    "deviceScaleFactor": 1,
                    "disabled": false
                  },
                  "throttlingMethod": "simulate"
                }
              },
              "upload": {
                "target": "filesystem",
                "outputDir": "./lhci-report-${{ matrix.formfactor.name }}"
              }
            }
          }
          EOF
        
      - name: Install Static Server and Wait-On
        run: |
          cd ${{ env.PROJECT_DIR }}
          npm install -g serve wait-on

      - name: Debug .env content
        run: |
          echo "Listing project files:"
          ls -al ${{ env.PROJECT_DIR }}
          echo "Showing .env content:"
          cat ${{ env.PROJECT_DIR }}/.env || echo ".env file not found"


      - name: Extract API URL from .env and export
        run: |
          cd ${{ env.PROJECT_DIR }}
          API_URL=$(grep REACT_APP_API_URL .env | cut -d '=' -f2 | xargs)
          echo "API_URL=$API_URL" >> $GITHUB_ENV
          echo "Exported API_URL: $API_URL"


      - name: Run Lighthouse Audit
        run: |
          cd ${{ env.PROJECT_DIR }}
          serve  -s build -l 3000 &  # Start static server in background
          wait-on http://localhost:3000
          sleep 3
          lhci autorun --config .lighthouserc.${{ matrix.formfactor.name }}.json
        env:
          PORT: 3000

      - name: Upload LHCI Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lhci-report-${{ matrix.formfactor.name }}
          path: ${{ env.PROJECT_DIR }}/lhci-report-${{ matrix.formfactor.name }}
