name: Detect .env Variables with Values

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  scan-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Find all .env files
        run: |
          # Find .env* files and join them with colon as separator
          ENV_FILES=$(find . -type f -name ".env*" | tr '\n' ':')
          echo "ENV_FILES=$ENV_FILES" >> $GITHUB_ENV
          echo "Found .env files: $ENV_FILES"

      - name: Extract variable names without values
        id: extract_vars
        run: |
          > env-vars-report.txt
          for file in ${ENV_FILES//:/ }; do
            if [ -f "$file" ]; then
              # Skip empty lines and comments, extract variable names only
              grep -E "^[A-Za-z_][A-Za-z0-9_]*=" "$file" | cut -d '=' -f 1 >> env-vars-report.txt
            fi
          done

          if [ -s env-vars-report.txt ]; then
            echo "Detected .env variables:"
            cat env-vars-report.txt
          else
            echo "No .env variables with values detected."
          fi

      - name: Upload .env variable report
        uses: actions/upload-artifact@v4
        with:
          name: env-vars-report
          path: env-vars-report.txt

      - name: Fail PR if .env variables found
        run: |
          if [ -s env-vars-report.txt ]; then
            echo "ERROR: .env variables pushed with values! See artifact 'env-vars-report'."
            exit 1
          fi
