name: Detect .env Variables with Values

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  scan-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Find all .env files
        run: |
          ENV_FILES=$(find . -type f -name ".env*")
          echo "Found .env files: $ENV_FILES"
          echo "$ENV_FILES" >> $GITHUB_ENV

      - name: Extract variable names without values
        id: extract_vars
        run: |
          > env-vars-report.txt
          for file in ${{ env.ENV_FILES }}; do
            # Skip empty lines and comments, extract variable names only
            grep -E "^[A-Za-z_][A-Za-z0-9_]*=" "$file" | cut -d '=' -f 1 >> env-vars-report.txt
          done
          if [ -s env-vars-report.txt ]; then
            echo "Detected variables in .env files:"
            cat env-vars-report.txt
          else
            echo "No variables with values detected."
          fi

      - name: Upload report as artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: env-vars-report
          path: env-vars-report.txt

      - name: Fail PR if .env variables found
        if: success()
        run: |
          if [ -s env-vars-report.txt ]; then
            echo "ERROR: .env variables pushed with values! See report."
            exit 1
          fi
